auto: true

markdown: kramdown
kramdown:
    input: GFM
rouge: true
permalink: /:title

title: Stay Hungry,Stay Foolish 
url: https://tangcong.github.io
feed: /atom.xml
author_info: <a href="https://tangcong.github.io/">Tang Cong</a>
